export const appRoute = {
  DASHBOARD: "Dashboard",
  HOME: "Home",
  PRODUCT_INVENTORY: "Inventory",
  SETTINGS: "Settings",
  LOGS: "Logs",
  ADD_PRODUCT: "Add Product",
  UPDATE_PRODUCT: "Update Product",
  SALES_HISTORY: "Sales History",
  CART: "Cart Items",
  CHECKOUT_SUCCESS: "CheckoutSuccess",
  PRODUCTS: "Product",
  POINT_OF_SALES: "Point of Sales",
  VIEW_TRANSACTION: "Transaction",
  AUTHENTICATE: "Authenticate",
};
